services:
  postgres:
    image: postgres
    restart: always
    shm_size: 128mb
    ports:
      - "5435:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
